#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


cd /app/core/
python manage.py collectstatic --noinput
python manage.py migrate
exec gunicorn core.wsgi:application -c "python:config.gunicorn"