version: '3'

volumes:
  django_logs_volume:
  django_media:
  db_volume:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    restart: always
    image: sakuras_sweets_backend
    volumes:
      - django_media:/core/media
      - django_logs_volume:/app/logs
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    command: /start
    networks:
      - sakuras_sweets
  
  db:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: db
    container_name: db
    restart: always
    volumes:
      - db_volume:/var/lib/posgresql/data
      - ./compose/local/postgres/backups:/backups
    ports:
      - 5432:5432
    networks:
      - sakuras_sweets
    env_file:
      - ./.env.db

  redis:
    image: redis:7.2.3
    restart: always
    networks:
      - sakuras_sweets

  celeryworker:
    <<: *django
    image: sakuras_sweets_celeryworker
    command: /start-celeryworker

  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    image: sakuras_sweets_backend_nginx
    depends_on:
      - django
    volumes:
      - ./app/static/:/app/core/static/
      - django_media:/usr/share/nginx/media
    ports:
      - 80:80
    networks:
      - sakuras_sweets

networks:
  sakuras_sweets:
    driver: bridge