# Generated by Django 4.2.7 on 2023-12-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип продукту')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('description', models.TextField(blank=True, max_length=6000, verbose_name='Опис')),
                ('quantity_in_stock', models.PositiveIntegerField(verbose_name='Кількість на складі')),
                ('product_quantity', models.PositiveIntegerField(verbose_name='Обсяг продукту')),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Знижка')),
                ('rating', models.SmallIntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('components', models.TextField(blank=True, null=True, verbose_name='Склад')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.producttype', verbose_name='Тип продукту')),
            ],
        ),
    ]
