# Generated by Django 4.2.7 on 2023-12-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_pricecurrency_currency_alter_product_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='pricecurrency',
            name='currency_symbol',
            field=models.CharField(default='₴', max_length=10, unique=True, verbose_name='Валютний символ'),
        ),
    ]
