# Generated by Django 4.2.7 on 2024-01-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecurrency',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='pricecurrency',
            name='currency_symbol',
            field=models.CharField(max_length=10, unique=True, verbose_name='Валютний символ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='components',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=6000, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
