# Generated by Django 4.2.7 on 2024-05-18 14:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_pricecurrency_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttype",
            options={},
        ),
        migrations.AlterField(
            model_name="product",
            name="components",
            field=models.TextField(
                blank=True, default="", max_length=500, null=True, verbose_name="Склад"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, default="", max_length=500, verbose_name="Опис"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="product.producttype",
                verbose_name="Тип продукту",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(
                blank=True,
                default=0.0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=70, verbose_name="Назва"),
        ),
    ]
