# Generated by Django 4.2.7 on 2024-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_producttype_options_alter_product_components_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(
                default="Виробник", max_length=100, verbose_name="Виробник"
            ),
            preserve_default=False,
        ),
    ]
