# Generated by Django 4.2.7 on 2024-05-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_product_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубліковано"),
        ),
    ]
