# Generated by Django 4.2.7 on 2024-05-15 22:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_producttype_options_alter_product_components_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product_rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productrating",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="productrating",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productrating",
            unique_together={("user", "product")},
        ),
    ]
