# Generated by Django 4.2.7 on 2024-05-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_rating", "0002_alter_productrating_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productrating",
            name="opinion",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Відгук"
            ),
        ),
    ]
