#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# Enter project folder
cd /app/core/

# Collect static and provide migrations
python manage.py collectstatic --noinput
python manage.py migrate

# Run server and compile messages
exec gunicorn core.wsgi:application -c "python:config.gunicorn" && python manage.py compilemessages