# Generated by Django 4.2.7 on 2024-05-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=128, unique=True, verbose_name="Email"),
        ),
    ]
